const images = {
    BackArrowBlue: require("../assets/images/BackArrowBlue.png"),
    BackArrowWhite: require("../assets/images/BackArrowWhite.png"),
    Categories: require("../assets/images/Categories.png"),
    Close: require("../assets/images/Close.png"),
    Follow: require("../assets/images/Follow.png"),
    Followers: require("../assets/images/Followers.png"),
    FollowWhite: require("../assets/images/FollowWhite.png"),
    Heart: require("../assets/images/Heart.png"),
    Home: require("../assets/images/Home.png"),
    Notification: require("../assets/images/Notification.png"),
    PickPhoto: require("../assets/images/PickPhoto.png"),
    Post: require("../assets/images/Post.png"),
    Reply: require("../assets/images/Reply.png"),
    Repost: require("../assets/images/Repost.png"),
    SearchBlue: require("../assets/images/SearchBlue.png"),
    SearchGray: require("../assets/images/SearchGray.png"),
    HeartOutline: require("../assets/images/HeartOutline.png"),

    HeartOutline2: require("../assets/images/HeartOutline2.png"),
    Heart2: require("../assets/images/Heart2.png"),
    Share: require("../assets/images/Share.png"),
    Comment: require("../assets/images/Comment.png"),
    UploadMedia: require("../assets/images/UploadMedia.png"),
    UploadVideo: require("../assets/images/UploadVideo.png"),
    SendMessage: require("../assets/images/SendMessage.png"),
    ThreeDots: require("../assets/images/ThreeDots.png"),
};
export default images;
